title: Sara Rosato
logo: /assets:img/IMG_2007.JPG
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
sass:
  load_paths:
    - _sass
  style: compressed
includes:
  - style.css
