title: Sara Rosato
logo: /assets:img/IMG_2007.JPG
# description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
sass:
  load_paths:
    - _sass
  style: compressed
includes:
  - style.css
